### ISSUE TITLE
Handle CORS in a dedicated Service class and in the BaseResource class

### ISSUE THREAD

**Issue by ametaireau** [mozilla-services/readinglist#132] opened 2015-02-19 14:57 UTC
Currently, we're patching the default value of  `cornice.Service` class to configure CORS as we want.

We shouldn't do that and instead create our own Service class from which we inherit, and do the same for BaseResource.

**Comment by leplatrem** [comment] 2015-03-17 13:46
Duplicate of https://github.com/mozilla-services/cliquet/issues/68

**Closed** 2015-03-17 14:04 UTC
Labels: refactoring
