### ISSUE TITLE
BATCH If path is not defined in defaults, "defaults.path in body: Required"

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/readinglist#112] opened 2015-02-10 12:44 UTC
```
$ cat batch_req.json
{
  "defaults": {
    "method" : "POST",
    "headers" : {}
  },
  "requests": [
    {
      "body" : {
        "path" : "/articles",
        "title": "MoFo",
        "url" : "http://mozilla.org"
      }
    },
    {
      "body" : {
        "path" : "/articles",
        "title": "MoCo",
        "url" : "http://mozilla.com"
      }
    }
  ]
}
```

Req:

```
$ http -a niko:niko POST http://0.0.0.0:8000/v0/batch < batch_req.json
HTTP/1.1 400 Bad Request
Content-Length: 104
Content-Type: application/json; charset=UTF-8
Date: Tue, 10 Feb 2015 12:44:37 GMT
Server: waitress

{
    "code": 400,
    "errno": 107,
    "error": "Invalid parameters",
    "message": "defaults.path in body: Required"
}
```

**Comment by leplatrem** [comment] 2015-02-10 13:51
This is a duplicate of #111 

Currently removing requirement of defaults path is done during the schema deserialization. Which is not called by Cornice.

**Closed by leplatrem** 2015-02-10 13:51 UTC
